

export const SUITE_PRODUCTS = [
  {
    id: 'ai-receptionist',
    icon: '🤖',
    name: 'AI Receptionist',
    tag: 'LIVE' as const,
    accent: 'text-sky-800',
    accentBg: 'bg-sky-50',
    accentBorder: 'border-sky-200',
    accentBtn: 'bg-sky-800 text-white hover:bg-sky-900',
    accentBtnOutline: 'border-sky-800 text-sky-800 hover:bg-sky-50',
    desc: 'Your WhatsApp, Instagram DMs, and Facebook — handled 24/7 by AI. Replies in Pidgin, Yoruba, Igbo, Hausa.',
    price: '₦20k–₦50k/mo',
    cta: 'Book Demo',
    href: '/receptionist',
    stat: '24/7',
    statLabel: 'Always on',
  },
  {
    id: 'digital-storefronts',
    icon: '🏪',
    name: 'Digital Storefronts',
    tag: 'LIVE' as const,
    accent: 'text-orange-900',
    accentBg: 'bg-orange-50',
    accentBorder: 'border-orange-200',
    accentBtn: 'bg-orange-900 text-white hover:bg-orange-950',
    accentBtnOutline: 'border-orange-900 text-orange-900 hover:bg-orange-50',
    desc: 'Launch your online store in 5 minutes. Paystack payments, inventory management, WhatsApp order notifications.',
    price: '₦2k/mo + 1%',
    cta: 'Try Storefronts',
    href: '/store',
    stat: '5 min',
    statLabel: 'Store live',
  },
  {
    id: 'credibility-hubs',
    icon: '💼',
    name: 'Credibility Hubs',
    tag: 'LIVE' as const,
    accent: 'text-indigo-900',
    accentBg: 'bg-indigo-50',
    accentBorder: 'border-indigo-200',
    accentBtn: 'bg-indigo-900 text-white hover:bg-indigo-950',
    accentBtnOutline: 'border-indigo-900 text-indigo-900 hover:bg-indigo-50',
    desc: 'Portfolio site + LinkedIn optimizer + ATS resume. Built for Nigerian professionals who need to look credible.',
    price: '₦5k once · ₦15k Pro',
    cta: 'Build Portfolio',
    href: '/credibility',
    stat: '₦5k',
    statLabel: 'one time',
  },
  {
    id: 'branding-design',
    icon: '🎨',
    name: 'Branding & Design',
    tag: 'LIVE' as const,
    accent: 'text-fuchsia-900',
    accentBg: 'bg-fuchsia-50',
    accentBorder: 'border-fuchsia-200',
    accentBtn: 'bg-fuchsia-700 text-white hover:bg-fuchsia-800',
    accentBtnOutline: 'border-fuchsia-700 text-fuchsia-700 hover:bg-fuchsia-50',
    desc: 'Logo, brand kit, WhatsApp flyer, social media kit. No designer. No agency. AI-generated and yours instantly.',
    price: '₦3k (Logo) · ₦8k (Kit)',
    cta: 'Generate Brand',
    href: '/branding',
    stat: '₦0',
    statLabel: 'vs ₦150k agency',
  },
  {
    id: 'viralkit',
    icon: '🎬',
    name: 'ViralKit',
    tag: 'LIVE' as const,
    accent: 'text-violet-800',
    accentBg: 'bg-violet-50',
    accentBorder: 'border-violet-200',
    accentBtn: 'bg-violet-700 text-white hover:bg-violet-800',
    accentBtnOutline: 'border-violet-700 text-violet-700 hover:bg-violet-50',
    desc: 'AI content calendar, caption generator & scheduler. Post to Instagram, TikTok, Facebook, X in one click.',
    price: '₦5k–₦25k/mo',
    cta: 'Start Creating',
    href: '/viralkit',
    stat: '8',
    statLabel: 'platforms at once',
  },
  {
    id: 'marketing-automation',
    icon: '📧',
    name: 'Marketing Automation',
    tag: 'BUILDING' as const,
    accent: 'text-purple-800',
    accentBg: 'bg-purple-50',
    accentBorder: 'border-purple-200',
    accentBtn: 'bg-purple-700 text-white hover:bg-purple-800',
    accentBtnOutline: 'border-purple-700 text-purple-700 hover:bg-purple-50',
    desc: 'AI email campaigns, WhatsApp broadcast sequences, and lead nurturing — built for Nigerian compliance.',
    price: '₦10k/month',
    cta: 'Join Waitlist',
    href: '/marketing',
    stat: '80%',
    statLabel: 'less manual work',
  },
  {
    id: 'emailscraper-pro',
    icon: '🔍',
    name: 'EmailScraper Pro',
    tag: 'LIVE' as const,
    accent: 'text-sky-900',
    accentBg: 'bg-sky-50',
    accentBorder: 'border-sky-200',
    accentBtn: 'bg-sky-700 text-white hover:bg-sky-800',
    accentBtnOutline: 'border-sky-700 text-sky-700 hover:bg-sky-50',
    desc: 'Find verified emails from LinkedIn, CAC Nigeria registry, and business directories. Bulk export + Chrome extension.',
    price: 'Free (50) · ₦5k–₦50k/mo',
    cta: 'Start Scraping',
    href: '/emailscraper',
    stat: '60s',
    statLabel: 'per contact found',
  },
  {
    id: 'analytics-dashboard',
    icon: '📊',
    name: 'Analytics Dashboard',
    tag: 'LIVE' as const,
    accent: 'text-slate-900',
    accentBg: 'bg-slate-50',
    accentBorder: 'border-slate-200',
    accentBtn: 'bg-slate-800 text-white hover:bg-slate-900',
    accentBtnOutline: 'border-slate-800 text-slate-800 hover:bg-slate-50',
    desc: 'Instagram, TikTok, Paystack, and website analytics — all in one Naira-first dashboard. Know your numbers.',
    price: '₦8k/month',
    cta: 'See Numbers',
    href: '/analytics',
    stat: '1',
    statLabel: 'dashboard, all channels',
  },
  {
    id: 'financial-forecasting',
    icon: '💰',
    name: 'Financial Forecasting',
    tag: 'BUILDING' as const,
    accent: 'text-emerald-900',
    accentBg: 'bg-emerald-50',
    accentBorder: 'border-emerald-200',
    accentBtn: 'bg-emerald-700 text-white hover:bg-emerald-800',
    accentBtnOutline: 'border-emerald-700 text-emerald-700 hover:bg-emerald-50',
    desc: '12-month cashflow projections. Scenario planning. Naira inflation adjustment. Connect Paystack for real data.',
    price: '₦8k/month',
    cta: 'Model Cashflow',
    href: '/finance',
    stat: '12mo',
    statLabel: 'projections',
  },
  {
    id: 'business-planning',
    icon: '📋',
    name: 'AI Business Planning',
    tag: 'BUILDING' as const,
    accent: 'text-blue-900',
    accentBg: 'bg-blue-50',
    accentBorder: 'border-blue-200',
    accentBtn: 'bg-blue-800 text-white hover:bg-blue-900',
    accentBtnOutline: 'border-blue-800 text-blue-800 hover:bg-blue-50',
    desc: 'Bank-ready Nigerian business plans, pitch decks, and market analysis — in under 10 minutes.',
    price: '₦10k per plan · ₦25k bundle',
    cta: 'Generate Plan',
    href: '/planning',
    stat: '10 min',
    statLabel: 'bank-ready plan',
  },
{
  id: 'naija-fit',
  icon: '💪',
  name: 'NaijaFit',
  accent: 'text-emerald-900',
  accentBg: 'bg-emerald-50',
  accentBorder: 'border-emerald-200',
  accentBtn: 'bg-emerald-700 text-white hover:bg-emerald-800',
  accentBtnOutline: 'border-emerald-700 text-emerald-700 hover:bg-emerald-50',
  desc: 'Nigerian fitness platform',
  stat: '500+',
  statLabel: 'meals in database',
  price: 'Free | ₦3k/month (Pro) | ₦8k/month (Coaching)',
  cta: 'Start NaijaFit →',
  href: '/fit',
  tag: 'LIVE' as const,
},
{
  id: 'investor-readiness',
  icon: '📈',
  name: 'Investor Readiness',
  accent: 'text-amber-900',
  accentBg: 'bg-amber-50',
  accentBorder: 'border-amber-200',
  accentBtn: 'bg-amber-900 text-white hover:bg-amber-950',
  accentBtnOutline: 'border-amber-900 text-amber-900 hover:bg-amber-50',
  desc: 'Get investor-ready with AI-generated pitch decks, financial models, and investor lists tailored to Nigerian startups.',
  stat: '80%',
  statLabel: 'less time preparing',
  price: '₦15k per deck · ₦40k bundle',
  cta: 'Get Investor Ready',
  href: '/investor',
  tag: 'PLANNED' as const,
}
];

export const PRICING_TIERS = [
  {
    name: 'Starter',
    price: '₦5,000',
    period: '/month',
    desc: 'One powerful tool. Start proving ROI.',
    features: [
      '1 PlanAI tool of your choice',
      'Up to 3 social accounts',
      'Basic analytics',
      'Email support',
      'BoldMind account (SSO)',
    ],
    cta: 'Start Free Trial',
    highlight: false,
    plan: 'starter',
  },
  {
    name: 'Pro',
    price: '₦15,000',
    period: '/month',
    desc: 'The full suite. Everything unlocked.',
    features: [
      'All PlanAI tools',
      'Unlimited leads & contacts',
      '10 social accounts',
      'WhatsApp alerts',
      'Team seats (3 members)',
      'Priority support',
      'ViralKit included',
    ],
    cta: 'Get Pro',
    highlight: true,
    plan: 'pro',
  },
  {
    name: 'Agency',
    price: '₦40,000',
    period: '/month',
    desc: 'Resell under your brand to clients.',
    features: [
      'Everything in Pro',
      'White-label option',
      'Unlimited client accounts',
      'API access',
      'Dedicated account manager',
      'Custom onboarding',
    ],
    cta: 'Contact Sales',
    highlight: false,
    plan: 'agency',
  },
];
